# Generated by Django 4.1.3 on 2022-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='true_or_false',
            field=models.BooleanField(default=False, verbose_name='Праильный ответ или нет'),
        ),
    ]
