# Generated by Django 4.1.3 on 2022-12-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_remove_question_test_remove_test_user_test_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='сhoice',
            new_name='choice_answer',
        ),
    ]
