# Generated by Django 4.1.3 on 2022-12-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_rename_сhoice_question_choice_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('pub_date',), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='testtasks',
            name='all_point_test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtasks',
            name='true_in_test',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
